### PR TITLE
Feature: Add edit with VS Code button

### LINKED ISSUE #188: Feature: Add edit code with VSCode button to repository code page
### Before you start...

- [X] Have you checked if a similar feature request has already been reported?

### Description

Simplest idea: integrate a magnet button to open system default `text-editor` (_Visual Studio Code, Atom, Sublime Text_, etc etc).

### Alternative solutions

In addition to that, we could integrate [`vscode.dev`](https://vscode.dev) inside a `chromium` instance so final user can code **directly inside **FluentHub****: for example, if I just had to add a link to `README.md` of an awesome-list, I'll click on "Edit in FluentHub" (or something similar), code and pull.

I can help you for both ideas.

### Relevant Assets

_No response_

### PR DESCRIPTION
**Pull request by Lamparter**
### 📄 Description

Add edit with VS Code button (and various other `GitCloneFlyout` changes

### 💭 Motivation and context

(Partially) fixes #188 and #495

---
```mermaid
sequenceDiagram
    participant User
    participant GitCloneFlyout
    participant ExternalApp
    participant Browser
    User->>GitCloneFlyout: Click clone button
    GitCloneFlyout->>ExternalApp: Attempt to open repository
    alt ExternalApp installed
        ExternalApp-->>GitCloneFlyout: Success
        GitCloneFlyout->>GitCloneFlyout: Log success
    else ExternalApp not installed
        ExternalApp-->>GitCloneFlyout: Failure
        GitCloneFlyout->>GitCloneFlyout: Log error
        GitCloneFlyout->>Browser: Open download page
        Browser-->>GitCloneFlyout: Success/Failure
        GitCloneFlyout->>GitCloneFlyout: Log result
    end
```

### CODE REVIEW

**Comment by Lamparter** [comment]
I think we should reduce the size of the button as well since there's lots of options
image
Need to add Code Insiders support as well.

**Comment by Lamparter** [comment]
Should navigate to VS(Code) download page when those events fail too

**Comment by Lamparter** [comment]
@0x5bfa I think we should merge. Could you review? I don't exactly remember what else I wanted to add 🥴

**Comment by Lamparter** [comment]
[`UWP Community > #dev-help`](https://discordapp.com/channels/372137812037730304/1286213586720653382/1286213586720653382) This is probably a stupid error...

**Comment by 0x5bfa** [comment]
@sourcery-ai review

**Comment by Lamparter** [comment]
This PR is finished. @0x5bfa requesting your review.

**Comment by 0x5bfa** [comment]
Thank you.

**Pull request merged**
