### PR TITLE
GitHub: Add security policy

### PR DESCRIPTION
**Pull request by Lamparter**

### CODE REVIEW

**Comment by 0x5bfa** [comment]
Let's not use emojis in this markdown.

**Comment by Lamparter** [comment]
Okay

**Comment by 0x5bfa** [comment]
@Lamparter Now it looks good to me

**Comment by 0x5bfa** [comment]
What do you think of commented out pieces, would we want to remove?
Otherwise, is it ready for merge?

**Review by 0x5bfa — APPROVED** [review]

**Comment by Lamparter** [comment]
Yes I implemented everything I wanted to implement as far as I remember
For the commented lines let's just leave them in because they are the default guide comments for a security.md file and at some point we may want to use the Supported versions text

**Pull request merged**
