### PR TITLE
GitHub: Update code of conduct

### PR DESCRIPTION
**Pull request by Lamparter**
### 📄 Description

Update code of conduct and other related community documents with better spelling/more accurate links.

#### 📋 Update community documents
- [x] Update code of conduct
- [x] Remove privacy policy
	- [x] Remove references to privacy policy
- [x] Add code of conduct to settings page
- [x] Fix merge conflicts

### CODE REVIEW

**Comment by Lamparter** [comment]
# 😕
image

**Comment by Lamparter** [comment]
I can't resolve these commits on the command line on my laptop

**Comment by Lamparter** [comment]
Finally! 😌 I managed to merge it using a series of very unintuitive powershell commands after a lot of trial and error.

**Comment by Lamparter** [comment]
@0x5bfa please review my merge commit as I didn't do it very well.

**Comment by Lamparter** [comment]
@0x5bfa do you want the licence to be a markdown file?
I'd say yes because it looks better on GitHub.

**Comment by Lamparter** [comment]
Can we just ignore these? @0x5bfa
image
I'm tired of working on this PR especially because it makes my old laptop very slow (due to changes across so many files)

**Comment by 0x5bfa** [comment]
Sure

**Comment by 0x5bfa** [comment]
Is this ready for merge?

**Review by 0x5bfa — APPROVED** [review]

**Comment by Lamparter** [comment]
Wait!

**Comment by Lamparter** [comment]
> Is this ready for merge?

You changed the name to `LICENSE`
I need to update the references to it everywhere

**Comment by Lamparter** [comment]
> Is this ready for merge?

Yes

**Comment by Lamparter** [comment]
Oh wait @0x5bfa you need to force merge it because CodeFactor is a required status check

**Comment by 0x5bfa** [comment]
Changed the rule

**Comment by 0x5bfa** [comment]
Thank you!

**Pull request merged**
